spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cc2?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456

      #正式环境
      #url: jdbc:mysql://mysql.sino-hanlin.tech:30002/cc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      #username: callcenter
      #password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true


##多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=cmp_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/cmp_security
#      username: root
#      password: 123456

#httpclient
httpclient:
  connectTimeout: 1000
  connectionRequestTimeout: 500
  defaultMaxPerRoute: 20
  maxTotal: 100
  socketTimeout: 10000
  staleConnectionCheckEnabled: true
  ukfUrl: http://localhost/touukf.html

# netty-socketio 配置
socketio:
  host: 192.168.31.94
  port: 9092
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  maxFramePayloadLength: 1048576
  maxHttpContentLength: 1048576
  pingInterval: 25000
  pingTimeout: 60000
  upgradeTimeout: 10000

